### ISSUE TITLE
Upgrade WebhookSender to rely on Guzzle 6

### ISSUE THREAD

**Issue by ivan-wolf** [detailnet/dfw-notification#4]
We're using a Guzzle version that is more than a year old...

https://github.com/guzzle/guzzle/releases

**Comment by sullenboom** [comment]
The Update to Guzzle 6 requires also a PHP Update to version 5.5.0 or newer.

We should also update the PHP version?

The Guzzle newest version for versions lower than PHP 5.5.0 are 5.3.0!

**Comment by ivan-wolf** [comment]
We should not rely on Guzzle at all, but allow for different HTTP clients to be used (see #15).
